#!/usr/bin/env bash

export NODE_ENV=test
ARGS=$@
# export TEST_FILES=${TEST_FILES:-(^node_modules*)/**/*.test.js} #zsh autocomplete only
export TEST_FILES=${ARGS:-`find . -name *.test.js -not -path "./node_modules*"`}

echo NODE_ENV=$NODE_ENV
echo TEST_FILES\($#\)=$TEST_FILES

set -o pipefail
ava --concurrency=4 --tap --serial $TEST_FILES | tee >(tap-summary) >(tap-xunit > ${TEST_XML:-/dev/null})
